application: photobooth-nacelle
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /static
  static_dir: static
  application_readable: true
- url: /.*
  script: nacelle.app.wsgi

inbound_services:
- warmup

libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "latest"
- name: webapp2
  version: "latest"
