site_name: Nacelle Microframework
dev_addr: 127.0.0.1:6060
repo_url: https://github.com/rehabstudio/nacelle
pages:
- ['index.md', 'Home']
- ['getting_started.md', 'Getting Started']
- ['about/contributing.md', 'About', 'Contributing to Nacelle']
- ['about/credits.md', 'About', 'Credits']
- ['about/license.md', 'About', 'License']
